<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" name="modelo.modelo_tests.TestArticulo-20160214112113" tests="7" time="0.161">
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test1_save_try" time="0.051"/>
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test2_save_except" time="0.008"/>
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test3_find" time="0.011"/>
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test3_notfind" time="0.010"/>
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test4_dlt" time="0.081"/>
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test4_dlt_except" time="0.001"/>
	<testcase classname="modelo.modelo_tests.TestArticulo" name="test5_repr" time="0.001"/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
